# this file is for the configuration of are project
#version
version: '3'
# all the services in our project
services: 
    app:
        build: 
            context: .
        ports: 
          - '8000:8000'
        volumes:
          - ./app:/app
        #make sure that you have one indent before you add a command
        command: > 
          sh -c "python manage.py wait_for_db && 
                 python manage.py migrate &&
                 python manage.py runserver 0.0.0.0:8000"
        environment: 
          - DB_HOST=db
          - DB_NAME=app
          - DB_USER=postgres
          - DB_PASS=supersecretpassword
        depends_on: 
          - db 
        
    db:   #new service, this is the image that locate the we will pull from dockerhub
       image: postgres:10-alpine
       #list of envirement variables
       environment: 
        - POSTGRES_DB=app
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=supersecretpassword  #you wouldn't use the same password for the prod.

