# this file is for the configuration of are project
#version
version: '3'
# all the services in our project
services: 
    app:
        build: 
            context: .
        ports: 
          - '8000:8000'
        volumes:
          - ./app:/app
        #make sure that you have one indent before you add a command
        command: > 
          sh -c "python manage.py runserver 0.0.0.0:8000"
        