# Generated by Django 3.0.3 on 2022-04-13 15:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('lunchroulette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchgroup',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.User', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='lunchgroup',
            name='number_people',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
    ]
