# Generated by Django 3.0.3 on 2022-04-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroulette', '0002_auto_20220413_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchgroup',
            name='admin',
        ),
    ]
