# Generated by Django 3.0.3 on 2022-04-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroulette', '0004_auto_20220413_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
