# Generated by Django 3.0.3 on 2022-04-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroulette', '0005_listplaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpartecipats',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='listplaces',
            name='restaurant_name',
            field=models.CharField(max_length=100, verbose_name='restaurant_name'),
        ),
    ]
