# Generated by Django 3.0.3 on 2022-04-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroulette', '0006_auto_20220417_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventPartecipats',
            new_name='Partecipats',
        ),
    ]
