# Generated by Django 3.0.3 on 2022-04-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroulette', '0007_auto_20220417_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partecipats',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name_partecipant'),
        ),
    ]
