# Generated by Django 3.0.3 on 2022-04-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroulette', '0008_auto_20220417_1313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListPlaces',
            new_name='ListPlace',
        ),
        migrations.RenameModel(
            old_name='Partecipats',
            new_name='Partecipat',
        ),
    ]
