# Generated by Django 3.0.3 on 2022-04-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroulette', '0009_auto_20220417_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partecipat',
            old_name='name',
            new_name='name_partecipant',
        ),
    ]
