# Generated by Django 3.0.3 on 2022-04-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroulette', '0010_auto_20220417_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchgroup',
            name='week_day',
            field=models.CharField(blank=True, max_length=100, verbose_name='week_day'),
        ),
    ]
