# Generated by Django 3.0.3 on 2022-04-19 18:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchroulette', '0011_lunchgroup_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchgroup',
            name='random_partecipants',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='random_partecipants'),
        ),
        migrations.AddField(
            model_name='lunchgroup',
            name='random_placeses',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='random_placeses'),
        ),
    ]
